name = "retropanning-worker"
main = "worker/src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"
not_found_handling = "single-page-application"

routes = [
  { pattern = "retro.rrodrigues.qzz.io", custom_domain = true }
]

[dev]
port = 8787
local_protocol = "http"
ip = "0.0.0.0"
